const data = {
  rent: [
    {
      name: 'lamborghini',
      model: 2017,
      image: '/images/car-3.png',
      price: 55.0,
      gaugeSimpleHigh: '16K',
      circlePause: 'Auto',
      plugCircleBolt: 'Auto',
    },
    {
      name: 'Ferrari',
      model: 2013,
      image: '/images/car-4.png',
      price: 60.0,
      gaugeSimpleHigh: '16K',
      circlePause: 'Auto',
      plugCircleBolt: 'Auto',
    },
    {
      name: 'Rolls Royce',
      model: 2018,
      image: '/images/car-5.png',
      price: 99.0,
      gaugeSimpleHigh: '16K',
      circlePause: 'Auto',
      plugCircleBolt: 'Auto',
    },
    {
      name: 'Batman',
      model: 1989,
      image: '/images/car-7.png',
      price: 55.0,
      gaugeSimpleHigh: '16K',
      circlePause: 'Auto',
      plugCircleBolt: 'Auto',
    },
    {
      name: 'dodge',
      model: 2010,
      image: '/images/car-8.png',
      price: 50.0,
      gaugeSimpleHigh: '16K',
      circlePause: 'Auto',
      plugCircleBolt: 'Auto',
    },
    {
      name: 'lamborghini',
      model: 2010,
      image: '/images/car-10.png',
      price: 55.0,
      gaugeSimpleHigh: '16K',
      circlePause: 'Auto',
      plugCircleBolt: 'Auto',
    },
    {
      name: 'Chevrolet',
      model: 2010,
      image: '/images/car-11.png',
      price: 45.0,
      gaugeSimpleHigh: '16K',
      circlePause: 'Auto',
      plugCircleBolt: 'Auto',
    },
    {
      name: 'Mercedes',
      model: 2010,
      image: '/images/car-12.png',
      price: 35.0,
      gaugeSimpleHigh: '16K',
      circlePause: 'Auto',
      plugCircleBolt: 'Auto',
    },
  ],
  brands: [
    { name: 'BMW', image: '/images/bmw-logo.png' },
    { name: 'Bugatti', image: '/images/bugatti-logo.png' },
    { name: 'lamborghini', image: '/images/Lamborghini-logo.png' },
    { name: 'Ferrari', image: '/images/Ferrari-logo.png' },
    { name: 'rolls', image: '/images/rolls-royce-logo.png' },
  ],
};
export default data;
